set_property SRC_FILE_INFO {cfile:{C:/Users/s0560839/Desktop/Vivado Labs/or2_gatter/or2_gatter.srcs/constrs_1/new/or2.xdc} rfile:../../../or2_gatter.srcs/constrs_1/new/or2.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property   PACKAGE_PIN F22  [get_ports a]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property   PACKAGE_PIN G22  [get_ports b]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property   PACKAGE_PIN T22  [get_ports y]
