@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Thu Dec 19 08:08:04 +0100 2019
REM SW Build 2700185 on Thu Oct 24 18:46:05 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto 87de4d4f53f04e13840802cf952b5e33 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot test_alu_cmp_behav xil_defaultlib.test_alu_cmp -log elaborate.log"
call xelab  -wto 87de4d4f53f04e13840802cf952b5e33 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot test_alu_cmp_behav xil_defaultlib.test_alu_cmp -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
